---
title: "Healthy Ride in Pittsburgh Flex Dashboard"
date: "September 20, 2018"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    orientation: row
    vertical_layout: fill
    theme: sandstone
    favicon: favicon.png
---

```{r setup, include=FALSE}
#require packages
library(flexdashboard)
library(shiny)
library(dplyr)
library(plotly)
library(reshape2)
library(shinythemes)
library(tibble)

#input data
ride <- read.csv('./ride.csv', head=TRUE)

#data cleaning
ride$Starttime <- NULL
ride$Stoptime <- NULL
ride$From.station.id <- NULL
ride$To.station.id <- NULL
ride$From.station.name <- NULL
ride$To.station.name <- NULL

ride <- ride%>%
  mutate(speedlevel = as.character(speedlevel),
         Usertype = as.factor(Usertype),
         Bikeid= as.factor(Bikeid))

rideInput <- reactive({
  ride.filter <- ride %>%
    #slider tripduration filter
    filter(Tripduration >= input$TripdurationSelect[1] & Tripduration <= input$TripdurationSelect[2])
  #selectinput speedlevel filter 
  if (length(input$SpeedSelect) > 0 ) {
    ride.filter <- subset(ride.filter, speedlevel%in% input$SpeedSelect)
  }
  #selecting bikeid filter 
  if (length(input$BikeidSelect) > 0 ) {
    ride.filter <- subset(ride.filter, Bikeid %in% input$BikeidSelect)
  }
  #check box usertype Filter
  ride.filter <- subset(ride.filter, Usertype%in%input$UserSelect)

  return(ride.filter)
})

mwInput <- reactive({
  rideInput() %>%
    melt(id = "Usertype")
})

pdf(NULL)
```

Sidebar {.sidebar}
=====================================

```{r}
selectInput("SpeedSelect",
            "Choose the Speed Range:",
            choices = sort(unique(ride$speedlevel)), 
            multiple = TRUE,
            selectize = TRUE,
            selected = c("1~10","10~20","20~30"))

sliderInput("TripdurationSelect",
            "Trip Duration:",
            min = min(ride$Tripduration, na.rm = T),
            max = max(ride$Tripduration, na.rm = T),
            value = c("80", "151106"),
            step = 1)
selectInput("BikeidSelect",
               "Bike ID:",
               choices = sort(unique(ride$Bikeid)),
               multiple = TRUE,
               selectize = TRUE,
               selected = c("70043", "70000","70007","70245","70063"))

checkboxGroupInput("UserSelect",
                   "User Type:",
                   choices = sort(unique(ride$Usertype)),
                   selected = c("Customer","Subscriber"))

```

Plot
=====================================

Row 
-------------------------------------

###

```{r}
renderValueBox({
    rd <- rideInput()
    num <- round(mean(rd$Speed, na.rm = T), 2)
    valueBox(caption = "Average Speed", value = num, icon = "fa-balance-scale", color = "info")
})
```

###

```{r}
renderValueBox({
  rd <- rideInput()
  num <- round(mean(rd$Tripduration, na.rm = T), 2)
  valueBox(caption = "Average Trip Duration", value = num, icon = "fa-sort-numeric-asc", color = "success")
})
```

### Bike Selected

```{r}
renderGauge({
  rate <- round(as.numeric(length(input$BikeidSelect)) / length(unique(ride$Bikeid))*100, 1)
  gauge(rate,min=0.0003,max=100,symbol = "%")
})
```

Row {.tabset .tabset-fade}
-------------------------------------

### Speed & Tripduration

```{r}
renderPlotly({
    dat <- rideInput()
    ggplotly(
      ggplot(data = dat, aes(x = Speed, y = Tripduration, color = Usertype))+geom_point())
  })
```

### Usertype & Speed

```{r}
renderPlotly({
    dat <- rideInput()
    ggplotly(
      ggplot(data = dat, aes(x = Usertype, y = Speed))+geom_boxplot())})
```


### Usertype & Bike
```{r}
renderPlotly({
  dat <- rideInput()
  ggplotly(
    ggplot(data = dat, aes(x = Usertype,fill=Bikeid))+geom_bar())})
```

Table
=====================================

Row 
-------------------------------------

### Table 

```{r}
DT::renderDataTable({
  ride.filter<- rideInput()
  subset(ride.filter,select =c(Trip.id,Usertype,Tripduration,Speed,speedlevel,Bikeid))
})
```

Row
-------------------------------------


```{r}
library(shiny)

ui <- fluidPage(
  
)

server <- function(input, output, session) {
  
}

shinyApp(ui, server)
```

